security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_PARENT:      ROLE_PARENT
        ROLE_STAFF:       ROLE_STAFF
        ROLE_ADMIN:       [ROLE_USER,ROLE_STAFF,ROLE_PARENT]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            access_denied_handler: security.access.handler

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reclamer/*, role: ROLE_PARENT}
        - { path: ^/demande/*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/admin/, role: ROLE_ADMIN }